# Generated by Django 6.1 on 2026-08-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member_membership_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'যাচাই অপেক্ষমাণ'), ('verified', 'যাচাইকৃত'), ('rejected', 'বাতিল'), ('blocked', 'ব্লক করা হয়েছে')], default='pending', max_length=20),
        ),
    ]
